name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true # fetches vcpkg into the root directory and other submodules into the 'extern' directory
          fetch-depth: 0 # to describe a tag during manual dispatches, fetching all history is required

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.28'  # Replace with the desired version of CMake
