name: Build

on:
  workflow_dispatch:

env: 
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64]
      fail-fast: false # allow other matrix entries to continue even if one fails

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true # fetches vcpkg into the root directory and other submodules into the 'extern' directory
          fetch-depth: 0 # to describe a tag during manual dispatches, fetching all history is required

      - uses: lukka/get-cmake@latest

      - name: Configure Project
        run: cmake --preset release

      - name: Build Project
        run: cmake --build --preset release
